services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-php
    volumes:
      - ./:/var/www/html:cached
    ports:
      - "9000:9000"
      - "9001:9003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
      image: nginx:alpine-slim
      container_name: ${PROJECT_NAME}-nginx
      ports:
        - "80:80"
      volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
